app/models.py
from app import db
from flask_login import UserMixin
from datetime import datetime as dt
from werkzeug.security import generate_password_hash, check_password_hash
from app import login


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    email = db.Column(db.String(150), unique=True, index=True)
    password = db.Column(db.String(200))
    icon = db.Column(db.Integer)
    created_on = db.Column(db.DateTime, default=dt.utcnow)

    def __repr__(self):
        return f'<User: {self.id} | {self.email}>'

    def from_dict(self, data):
        self.first_name = data["first_name"]
        self.last_name = data["last_name"]
        self.email = data['email']
        self.icon = data['icon']
        self.password = self.hash_password(data['password'])

    # salts and hashes our password to make it hard to steal
    def hash_password(self, original_password):
        return generate_password_hash(original_password)

    # compares the user passsword to the password provided in the login form
    def check_password_hash(self, login_password):
        return check_password_hash(self.password, login_password)

    # save the user to the database
    def save(self):
        db.session.add(self)  # add the user to the db session
        db.session.commit()  # save everything in the session to the database

    def get_icon_url(self):
        return f'https://avatars.dicebear.com/api/adventurer/{self.icon}.svg'


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

    # SELECT * FROM user WHERE id =???

app/__init__.py
from flask import Flask
from config import Config
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


login = LoginManager()
login.login_view = 'auth.login'

# init the database
db = SQLAlchemy()
migrate = Migrate()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    # register plugins
    login.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    # register our blueprints with the app
    from .blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from .blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    return app

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__, url_prefix='')

from .import routes


app/blueprints/main/routes.py
from flask import render_template, request
import requests
from flask_login import login_required
from .import bp as main


@main.route('/', methods=['GET'])
@login_required
def index():
    return render_template('index.html.j2')


@main.route('/trainers', methods=['GET'])
@login_required
def trainers():
    my_trainers = ["Ash", "Misty", "Brock", "Garry"]
    # name inside of HTML = name in python
    return render_template("trainers.html.j2", trainers=my_trainers)


@main.route('/pokedex', methods=['GET', 'POST'])
@login_required
def pokedex():
    if request.method == 'POST':
        pokemon_name = request.form.get('pokemon_name')
        # sprites = request.form.get('sprites')
        url = f"https://pokeapi.co/api/v2/pokemon/{pokemon_name}"
        response = requests.get(url)

        if response.ok:
            # request worked
            if not response.json():
                error_string = "We have a problem loading the database"
                return render_template('pokedex.html.j2', error=error_string)
            data = response.json()
            pokemon_dict = {}
            pokemon = {
                "Name": data['forms'][0]['name'],
                "Base Stat HP": data['stats'][0]['base_stat'],
                "Base Stat Defense": data['stats'][1]['base_stat'],
                "Base Stat Attack": data['stats'][2]['base_stat'],
                "Sprite URL": data['sprites']['front_shiny']
            }
            print(pokemon)
            return render_template('pokedex.html.j2', pokemon=pokemon)

        else:
            error_string = "The database is on lunch break"
            return render_template('pokedex.html.j2', error=error_string)
    # the request fail

    return render_template('pokedex.html.j2')

app/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {# favorite icon #}
    <link rel="shortcut icon" href="{{url_for('static',filename='images/pokemonicon.ico')}}" type="image/x-icon">
    <link rel="pokemon-touch-icon" sizes="180x180" href="{{url_for('static',filename='images/pokemon-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{url_for('static',filename='images/pokemon-icon32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{url_for('static',filename='images/pokemon-icon16x16.png')}}">
    <!-- Bootstrap CSS -->
    
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{{url_for('static',filename='css/base.css')}}">
    {% block css %}

    {% endblock %}
<!-- change this -->
    <title>
        {% block title %}
        {% endblock %}
    </title>
  </head>
  <body>
    {% include './includes/nav.html.j2' %}
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for class, message in messages %}
            <div class="alert alert-{{class}} alert-dismissible fade show" role="alert">
              {{message}}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">
    {% block content %}
    {% endblock %}
    </div>


    <!-- Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/includes/nav.html.j2
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('main.index')}}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{url_for('main.index')}}">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.trainers')}}">Trainers</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.pokedex')}}">Pokedex</a>
            </li>
            
        {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.register')}}">Register</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{{url_for('auth.login')}}">Login</a>
            </li>
        {% endif %}
    </ul>

        {% if current_user.is_authenticated %}  
        <ul class="navbar-nav ms-auto align-items-center" >
            <img src="{{current_user.get_icon_url()}}" style="height:50px">
            <li class="nav-item">
                <div class="row">
                <div class="col-12">
                    <a class="nav-link" href="{{url_for('auth.logout')}}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-door-closed-fill" viewBox="0 0 16 16">
                    <path d="M12 1a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2a1 1 0 0 1 1-1h8zm-2 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                    </svg>
                    </a>
                </div>

                <div class="col-12">
                    <a class="nav-link" href="{{url_for('auth.edit_profile')}}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear-wide-connected" viewBox="0 0 16 16">
                    <path d="M7.068.727c.243-.97 1.62-.97 1.864 0l.071.286a.96.96 0 0 0 1.622.434l.205-.211c.695-.719 1.888-.03 1.613.931l-.08.284a.96.96 0 0 0 1.187 1.187l.283-.081c.96-.275 1.65.918.931 1.613l-.211.205a.96.96 0 0 0 .434 1.622l.286.071c.97.243.97 1.62 0 1.864l-.286.071a.96.96 0 0 0-.434 1.622l.211.205c.719.695.03 1.888-.931 1.613l-.284-.08a.96.96 0 0 0-1.187 1.187l.081.283c.275.96-.918 1.65-1.613.931l-.205-.211a.96.96 0 0 0-1.622.434l-.071.286c-.243.97-1.62.97-1.864 0l-.071-.286a.96.96 0 0 0-1.622-.434l-.205.211c-.695.719-1.888.03-1.613-.931l.08-.284a.96.96 0 0 0-1.186-1.187l-.284.081c-.96.275-1.65-.918-.931-1.613l.211-.205a.96.96 0 0 0-.434-1.622l-.286-.071c-.97-.243-.97-1.62 0-1.864l.286-.071a.96.96 0 0 0 .434-1.622l-.211-.205c-.719-.695-.03-1.888.931-1.613l.284.08a.96.96 0 0 0 1.187-1.186l-.081-.284c-.275-.96.918-1.65 1.613-.931l.205.211a.96.96 0 0 0 1.622-.434l.071-.286zM12.973 8.5H8.25l-2.834 3.779A4.998 4.998 0 0 0 12.973 8.5zm0-1a4.998 4.998 0 0 0-7.557-3.779l2.834 3.78h4.723zM5.048 3.967c-.03.021-.058.043-.087.065l.087-.065zm-.431.355A4.984 4.984 0 0 0 3.002 8c0 1.455.622 2.765 1.615 3.678L7.375 8 4.617 4.322zm.344 7.646.087.065-.087-.065z"/>
                    </svg>
                    </a>   
                </div>
                </div>
        </ul>
        {% endif %}
    
    </div>
</div>
</nav>

app/templates/index.html.j2
{% extends 'base.html.j2' %}

{% block title %}
  Welcome Users
{% endblock %}

{% block content %}
<h1>Welcome Home Trainers</h1>
{% endblock %}

app/templates/login.html.j2
{% extends 'base.html.j2'%}
{% block css %}
  <link rel="stylesheet" href="{{url_for('static',filename='css/login.css')}}">
{% endblock %}
{% block title%}
Login
{% endblock %}

{% block content%}
<h1>Login</h1>
<small style = "color:red;">{{error}}</small>
<form action="{{url_for('auth.login')}}" method ="POST">
    {{form.hidden_tag()}}
  <br>  
  <div>
    {{form.email.label(class="form-label")}}
    {{form.email(class="form-control")}}
    {% for error in form.email.errors %}
    <small style = "color:red">{{error}}</small>
    {% endfor %}
  </div>
  <br>
  <div>
    {{form.password.label(class="form-label")}}
    {{form.password(class="form-control")}}
    {% for error in form.password.errors %}
    <small style = "color:red;">{{error}}</small>
    {% endfor %}
  </div>
  <br>

  <div>
    {{form.submit(class= "btn btn-primary form-control")}}
  </div>
</form>

{% endblock %}

app/templates/pokedex.html.j2
{% extends 'base.html.j2'%}
{% block css %}
  <link rel="stylesheet" href="{{url_for('static',filename='css/pokedex.css')}}">
{% endblock %}
{% block title %}
    Pokedex
{% endblock %}

{% block content %}
<h1>World Wide Pokedex</h1>
<form method="POST" action='/pokedex'>
  <div class="mb-3">
    <label for="pokemon_name" class="form-label">Pokemon Name</label>
    <input type="text" name="pokemon_name" class="form-control" id="pokemon_name" >
    <div id="textHelp" class="form-text">Let use expand your knowledge</div>
  </div>
  
  <!-- <div class="mb-3"> -->
    <!-- <label for="sprites" class="form-label">Sprites</label> -->
    <!-- <input type="text" name= "sprites"  class="form-control" id="sprites"> -->
    <!-- <div id="textHelp" class="form-text">Please enter front_shiny</div> -->
  <!-- </div> -->
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<small style = "color:red;">{{error}}</small>
<br>

{% if pokemon %}
    <table class="table table-dark table-hover">
    <thead>
        <tr>
        <th scope="col">Name</th>
        <th scope="col">Base Stat HP</th>
        <th scope="col">Base Stat Defense</th>
        <th scope="col">Base Stat Attack</th>
        <th scope="col">Sprite URL</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">{{pokemon['Name']}}</th>
            <td>{{pokemon['Base Stat HP']}}</td>
            <td>{{pokemon['Base Stat Defense']}}</td>
            <td>{{pokemon['Base Stat Attack']}}</td>
            <td><img src="{{pokemon['Sprite URL']}}" height=100 width=100></td>
        </tr>   
    </tbody>
    </table>
{% else %}
Enter the name of the pokemon you want
{% endif %}
{% endblock %}

app/templates/register.html.j2
{% extends 'base.html.j2'%}
{% block title%}
Register
{% endblock %}
{%block content%}
<h1>
{% if current_user.is_aunthenticated %}
    Edit Profile 
{% else %}
    Register
{% endif %}
</h1>
<small style = "color:red;">{{error}}</small>
<form action="{{url_for('auth.edit_profile') if current_user.is_authenticated else url_for('auth.register')}}" method="POST">
    {{form.hidden_tag()}}
    {# avatar section #}
    {{form.icon.label}}<br>
    {% for subfield in form.icon %}
        {{subfield}}
        {{subfield.label | safe}}
    {% endfor %}
    <br>


    {# first #}
    {{form.first_name.label(class="form-label")}}
    {{form.first_name(class="form-control", value=current_user.first_name)}}

    {# last name #}
    {{form.last_name.label(class="form-label")}}
    {{form.last_name(class="form-control",value=current_user.first_name)}}

    {# email #}
    {{form.email.label(class="form-label")}}
    {{form.email(class="form-control", value=current_user.first_name)}}
    {# email error #}
    {% for error in form.email.errors %}
        <small style="color:red;">{{error}}</small><br>
    {% endfor %}

    {# password #}
    {{form.password.label(class="form-label")}}
    {{form.password(class="form-control")}}

    {# confirm password #}
    {{form.confirm_password.label(class="form-label")}}
    {{form.confirm_password(class="form-control")}}

    {# password error #}
    {% for error in form.password.errors %}
        <small style="color:red;">{{error}}</small><br>
    {% endfor %}
    <br>
    {# submit button #}
    {{form.submit(class='btn btn-primary')}}

</form>
{% endblock %}

app/templates/trainers.html.j2
{% extends 'base.html.j2' %}
{% block css %}
  <link rel="stylesheet" href="{{url_for('static',filename='css/trainers.css')}}">
{% endblock %}
{% block title%}
  Hello Trainers
{% endblock %}

{% block content %}
<h1>My Trainers</h1>
<ul>
  {% for trainer in trainers %}
    <li>{{trainer}}</li>
  {% endfor %}
</ul>
{% endblock %}